In [1]:
from binance.client import Client as bnb_client
from datetime import datetime
import pandas as pd

In [10]:

client = bnb_client()

def get_binance_px(symbol,freq,start_ts = '2020-01-01'):
    data = client.get_historical_klines(symbol,freq,start_ts)
    columns = ['open_time','open','high','low','close','volume','close_time','quote_volume',
    'num_trades','taker_base_volume','taker_quote_volume','ignore']

    data = pd.DataFrame(data,columns = columns)
    
    # Convert from POSIX timestamp (number of millisecond since jan 1, 1970)
    data['open_time'] = data['open_time'].map(lambda x: datetime.utcfromtimestamp(x/1000))
    data['close_time'] = data['close_time'].map(lambda x: datetime.utcfromtimestamp(x/1000))
    return data 

univ = ['BTCUSDT','ETHUSDT','ADAUSDT','BNBUSDT','XRPUSDT','DOTUSDT','MATICUSDT']

freq = '30m'
px = {}
for x in univ:
    data = get_binance_px(x,freq)
    px[x] = data.set_index('open_time')['close']

px = pd.DataFrame(px).astype(float)
px = px.reindex(pd.date_range(px.index[0],px.index[-1],freq=freq))

C:\Users\parra\AppData\Local\Temp\ipykernel_6756\3454781459.py:11: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  data['open_time'] = data['open_time'].map(lambda x: datetime.utcfromtimestamp(x/1000))
C:\Users\parra\AppData\Local\Temp\ipykernel_6756\3454781459.py:12: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  data['close_time'] = data['close_time'].map(lambda x: datetime.utcfromtimestamp(x/1000))
C:\Users\parra\AppData\Local\Temp\ipykernel_6756\3454781459.py:24: FutureWarning: 'm' is deprecated and will be removed in a future version, please use 'ME' instead.
  px = px.reindex(pd.date_range(px.index[0],px.index[-1],freq=freq))

In [11]:
px.to_pickle('crypto_30m_px.pk')

In [2]:
px = pd.read_pickle('crypto_30m_px.pk')

In [3]:
px.head()

              BTCUSDT  ETHUSDT  ADAUSDT   BNBUSDT  XRPUSDT  DOTUSDT  MATICUSDT
2020-01-31    9512.17   185.03  0.05626   18.6118  0.24437      NaN    0.01863
2022-07-31   23661.84  1697.73  0.52730  289.2000  0.39150    8.240    0.93210
2025-01-31  104763.56  3259.33  0.95680  677.4300  3.12230    6.143        NaN

In [4]:
ret = px.pct_change()

C:\Users\parra\AppData\Local\Temp\ipykernel_10148\4118645207.py:1: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  ret = px.pct_change()

In [5]:
ret.head()

,BTCUSDT,ETHUSDT,ADAUSDT,BNBUSDT,XRPUSDT,DOTUSDT,MATICUSDT
2020-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-07-31,1.487533,8.175431,8.372556,14.538529,0.602079,NaN,49.032206
2025-01-31,3.427532,0.919816,0.814527,1.342427,6.975223,-0.25449,0.000000